// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6rWNeLXtlHO8rnZ2rsI8Bpmgnw8ui1us',
    appId: '1:185785391363:android:fb1ef86bdcd4c9f7aef136',
    messagingSenderId: '185785391363',
    projectId: 'stc-production-150269',
    databaseURL: 'https://stc-production-150269.firebaseio.com',
    storageBucket: 'stc-production-150269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGHI5liG1Sd2a7HAhSXfArkRPNe1Acyxk',
    appId: '1:185785391363:ios:4ee62befebe854f9aef136',
    messagingSenderId: '185785391363',
    projectId: 'stc-production-150269',
    databaseURL: 'https://stc-production-150269.firebaseio.com',
    storageBucket: 'stc-production-150269.appspot.com',
    androidClientId: '185785391363-07i094vcr01vdtkkglclkbgg1c879jr3.apps.googleusercontent.com',
    iosClientId: '185785391363-ahml21jfpeh4iqtepi4g09gl1f9jji10.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthExample',
  );
}
